ZSH_THEME="powerlevel9k/powerlevel9k"

# Must have a nerd font installed - mono fonts tend to have spacing issues - https://github.com/ryanoasis/nerd-fonts
POWERLEVEL9K_MODE='nerdfont-complete'

# Prompt Options
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_HIDE_BRANCH_ICON=true

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\ue0c0 '
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status time dir vcs dir_writable)
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=' \ue0c2'
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time node_version)

# Last Command Status Segment
POWERLEVEL9K_OK_ICON='\ufca4'
POWERLEVEL9K_STATUS_OK_BACKGROUND='green'
POWERLEVEL9K_STATUS_OK_FOREGROUND='white'

POWERLEVEL9K_FAIL_ICON='\uf119'
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='red'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='253'

# Time Segment
POWERLEVEL9K_TIME_FOREGROUND='253'
POWERLEVEL9K_TIME_BACKGROUND='034'

# Directory Segment
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_DIR_PATH_SEPARATOR=$(echo -n " \uE0B1 ")

POWERLEVEL9K_DIR_HOME_BACKGROUND='028'
POWERLEVEL9K_DIR_HOME_FOREGROUND="253"

POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='022'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="253"

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="253"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="028"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="253"

# Version Control Section 
POWERLEVEL9K_VCS_GIT_ICON='\ue708'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\ue708'

# Advanced `vcs` color customization
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='253'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='059'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='253'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='002'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='253'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='064'

    
# Execution Time Segment
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='196'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='253'

# NVM Version Segment
POWERLEVEL9K_NODE_ICON='\uf898'
POWERLEVEL9K_NODE_VERSION_BACKGROUND='202'
POWERLEVEL9K_NODE_VERSION_FOREGROUND='253'