ZSH_THEME="powerlevel9k/powerlevel9k"

# Must have a nerd font installed - mono fonts tend to have spacing issues - https://github.com/ryanoasis/nerd-fonts
POWERLEVEL9K_MODE='nerdfont-complete'

# Prompt Options
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_HIDE_BRANCH_ICON=true

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\ue0c0 '
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status time dir vcs dir_writable)
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=' \ue0c2'
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time nvm node_version)

# Directory Segment
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_DIR_PATH_SEPARATOR=$(echo -n " \uE0B1 ")
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="white"

# OS Icon Segment
POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"

# Execution Time Segment
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'

# Last Command Status Segment
POWERLEVEL9K_OK_ICON='\ufca4'
POWERLEVEL9K_STATUS_OK_BACKGROUND='green'
POWERLEVEL9K_STATUS_OK_FOREGROUND='white'

POWERLEVEL9K_FAIL_ICON='\uf119'
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='red'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='white'

# Version Control Section 
POWERLEVEL9K_VCS_GIT_ICON='\ue708'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\ue708'

# NVM Version Segment
POWERLEVEL9K_NODE_ICON='\uf898'
